apiVersion: apps/v1
kind: Deployment
metadata:
  name: poddy-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poddy
  template:
    metadata:
      labels:
        app: poddy
    spec:
      containers:
      - name: poddy
        image: poddy:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: poddy-service
spec:
  selector:
    app: poddy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: poddy-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poddy-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80